-- ==============================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR CREATORS DATABASE
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Create the creators table
CREATE TABLE IF NOT EXISTS public.creators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    name TEXT,
    email TEXT NOT NULL,
    phone TEXT DEFAULT '',
    followers TEXT,
    followers_num INTEGER DEFAULT 0,
    category TEXT DEFAULT 'Lifestyle / Content Creator',
    location TEXT DEFAULT 'USA',
    biography TEXT DEFAULT '',
    instagram_url TEXT NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    price TEXT DEFAULT '',
    rating TEXT DEFAULT '',
    package_offer TEXT DEFAULT '',
    external_url TEXT DEFAULT '',
    source TEXT DEFAULT 'Collabstr / Modash / Verified Public Profile',
    email_status TEXT DEFAULT 'not_sent', -- 'not_sent', 'sent', 'failed'
    last_emailed_at TIMESTAMP WITH TIME ZONE,
    email_subject TEXT DEFAULT '',
    email_body TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create index on username for fast lookups & upserts
CREATE INDEX IF NOT EXISTS idx_creators_username ON public.creators(username);

-- 3. Create index on email and email_status
CREATE INDEX IF NOT EXISTS idx_creators_email ON public.creators(email);
CREATE INDEX IF NOT EXISTS idx_creators_email_status ON public.creators(email_status);
CREATE INDEX IF NOT EXISTS idx_creators_created_at ON public.creators(created_at);

-- 4. Create index on category and follower counts for fast queries
CREATE INDEX IF NOT EXISTS idx_creators_category ON public.creators(category);
CREATE INDEX IF NOT EXISTS idx_creators_followers_num ON public.creators(followers_num);

-- 5. Auto-update updated_at timestamp trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS trigger_creators_updated_at ON public.creators;
CREATE TRIGGER trigger_creators_updated_at
    BEFORE UPDATE ON public.creators
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- Enable Row Level Security (RLS) - Optional
ALTER TABLE public.creators ENABLE ROW LEVEL SECURITY;

-- Allow public read/write if using anon key, or service_role bypasses RLS
CREATE POLICY "Allow all operations for authenticated and anon users" 
ON public.creators 
FOR ALL 
USING (true) 
WITH CHECK (true);
